### ISSUE TITLE
Unable to connect to Actual Server

### ISSUE THREAD

**Issue by latetedemelon** [jhonderson/actual-http-api#25]
I feel like a bit of a moron right now, I can't figure out what's going on.   I've set up a vanilla install of actual with this package as part of the same docker-compose.  No reverse proxies are involved.

```
name: Actual Stack
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualserver
    ports:
      - '5006:5006'
    environment:
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
    volumes:
      - ./actual-data:/data
    restart: unless-stopped

  actual-http-api:
    image: jhonderson/actual-http-api:latest
    container_name: actualhttpapi
    volumes:
      - ./data:/data:rw
    ports:
      - 5007:5007
    environment:
      - ACTUAL_SERVER_URL=${ACTUAL_SERVER_URL}
      - ACTUAL_SERVER_PASSWORD=${ACTUAL_SERVER_PASSWORD}
      - API_KEY=${API_KEY}
    restart: on-failure
```

```
ACTUAL_SERVER_URL=https://localhost:5006
ACTUAL_SERVER_PASSWORD=XXXX000X
API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Version 24.10.1, latest for actual-http-api

0 issues with Actual itself.  But I can't get get it to talk to actual.  I've tried:

- by docker container name (http and https)
- by localhost  (http and https)
- by IP  (http and https)

And consistently get:

```
{"error":"Error accessing Actual Server, check Actual Server password"}
```

I know I must be missing something, can someone help me out?

**Comment by jbalatero** [comment]
are you using a custom cert?

**Comment by latetedemelon** [comment]
> are you using a custom or self-signed cert?

I am, but I didn't even think a cert was required.  I tried with no cert and a self signed cert.  I can try a *signed* cert if that will make a difference.

**Comment by jhonderson** [comment]
Hey there, about ACTUAL_SERVER_URL, if both containers are in the same docker network, you don’t need to use https; this is not by default though, you either have to create a docker network and have both containers use it, or make both containers use bridge network.

If actual server is exposed to the public, you can directly use the actual server custom domain, instead of localhost.

**Comment by latetedemelon** [comment]
I’m not exposing it to the public, and my understanding was that by default
docker would create a bridge network for both these containers to be on.
I’ll try explicitly having a bridge, and a signed certificate later tonight
to test.

**Comment by latetedemelon** [comment]
If someone might be willing to test the stack, I posted that would be greatly appreciated.  Even hearing it works for other people would keep me from tilting at windmills.
________________________________

**Comment by jhonderson** [comment]
You are right, both containers run in bridge network by default, but then you cannot use localhost within a container. You have 2 options, either to use the name of the container, I.e http://actualserver:5006.

Or keep using localhost, but adding the option `network_mode: host`

See this related post: https://stackoverflow.com/a/56883398

**Comment by latetedemelon** [comment]
OK, still not clear why the IP or container name didn’t work but I’ll try again with a signed cert.
________________________________

**Comment by jhonderson** [comment]
I am going to try your setup locally. In the mean time, feel free to share the actual http api container logs to see if there are more details of the failure, I am guessing it’s an http timeout

**Comment by jhonderson** [comment]
I got it to work locally, here my setup:
```
name: test
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualserver
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
    restart: unless-stopped

  actual-http-api:
    image: jhonderson/actual-http-api:latest
    container_name: actualhttpapi
    volumes:
      - ./data:/data:rw
    ports:
      - 5007:5007
    environment:
      - ACTUAL_SERVER_URL=http://actualserver:5006
      - ACTUAL_SERVER_PASSWORD=test
      - API_KEY=test
    restart: on-failure
```

Here is the things you can double check:
1. Enter the actual web ui and setup a password. This may be obvious but if you don't have a budget created, nor a password for it, actual http api won't work
2. If you password has characters docker compose doesn't like, escape it like `- 'ACTUAL_SERVER_PASSWORD=problematic-password'`
