### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by gerardsyd** [jhonderson/actual-http-api#7]
Hi - thanks for this. I'm trying to access via the webUI and keep getting this error:
```
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
```

I'm not entirely sure what it means and not familiar with node to try and debug. Nothing is showing up in the docker logs so can't see where it's failing. 

Here is my actual set up and the set up for actual-http-api. Both are set up in docker containers:
```
  # Actual: Budgeting App
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - '5006:5006'
    environment:
       TZ: $TZ
       PUID: $PUID
       PGID: $PGID
    volumes:
      - ${DOCKERDIR}/shared/actual:/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.actual-rtr.entrypoints=https"
      - "traefik.http.routers.actual-rtr.rule=Host(`actual.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.actual-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.actual-rtr.service=actual-svc"
      - "traefik.http.services.actual-svc.loadbalancer.server.port=5006"

  # Actual API Access
  actualapi:
    container_name: actualapi
    image: jhonderson/actual-http-api:latest
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ${DOCKERDIR}/shared/actualapi/data:/data:rw
    ports:
      - '5007:5007'
    environment:
       TZ: $TZ
       PUID: $PUID
       PGID: $PGID
      ACTUAL_SERVER_URL: ${ACTUAL_SERVER_URL}
      ACTUAL_SERVER_PASSWORD: ${ACTUAL_SERVER_PASSWORD}
      API_KEY: ${ACTUAL_API_KEY}
```

The ACTUAL_SERVER_URL is set to my external url -> https://actual.DOMAINNAME

On the UI, I've tried both connecting to localhost as well as the {domainname} version but neither appears to work. 

Not sure if I need to set up the traefik access or whether I need them on the same server or if ACTUAL_SERVER_URL needs to point to the local IP address (which is problematic with the SSL certs). 

Any assistance would be appreciated. Thank you. 

EDIT: I should note that Actual sits behind traefik which is using google oauth in front of the password protection. Not sure if that could also be the issue.
